package dl;
// Generated 23-nov-2016 15:49:48 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatosEjercicio generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name="DatosEjercicio.findAll", query="SELECT d FROM DatosEjercicio d"),
	@NamedQuery(name="DatosEjercicio.findAllById", query="SELECT d FROM DatosEjercicio d  WHERE d.idDatosEjercicio= :idDatosEjercicio")
})
@Table(name = "DATOS_EJERCICIO")
public class DatosEjercicio implements java.io.Serializable {

	private Integer idDatosEjercicio;
	private String idEjercicio;
	private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);
	private Set<Resultados> resultadoses = new HashSet<Resultados>(0);
	private Set<TextoEnunciado> textoEnunciados = new HashSet<TextoEnunciado>(0);
	private Set<Audio> audios = new HashSet<Audio>(0);
	private Set<Imagen> imagens = new HashSet<Imagen>(0);

	public DatosEjercicio() {
	}

	public DatosEjercicio(String idEjercicio) {
		this.idEjercicio = idEjercicio;
	}

	public DatosEjercicio(String idEjercicio, Set<Respuesta> respuestas, Set<Resultados> resultadoses,
			Set<TextoEnunciado> textoEnunciados, Set<Audio> audios, Set<Imagen> imagens) {
		this.idEjercicio = idEjercicio;
		this.respuestas = respuestas;
		this.resultadoses = resultadoses;
		this.textoEnunciados = textoEnunciados;
		this.audios = audios;
		this.imagens = imagens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDATOS_EJERCICIO", unique = true, nullable = false)
	public Integer getIdDatosEjercicio() {
		return this.idDatosEjercicio;
	}

	public void setIdDatosEjercicio(Integer idDatosEjercicio) {
		this.idDatosEjercicio = idDatosEjercicio;
	}

	@Column(name = "idEJERCICIO", nullable = false, length = 45)
	public String getIdEjercicio() {
		return this.idEjercicio;
	}

	public void setIdEjercicio(String idEjercicio) {
		this.idEjercicio = idEjercicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosEjercicio")
	public Set<Respuesta> getRespuestas() {
		return this.respuestas;
	}

	public void setRespuestas(Set<Respuesta> respuestas) {
		this.respuestas = respuestas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosEjercicio")
	public Set<Resultados> getResultadoses() {
		return this.resultadoses;
	}

	public void setResultadoses(Set<Resultados> resultadoses) {
		this.resultadoses = resultadoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosEjercicio")
	public Set<TextoEnunciado> getTextoEnunciados() {
		return this.textoEnunciados;
	}

	public void setTextoEnunciados(Set<TextoEnunciado> textoEnunciados) {
		this.textoEnunciados = textoEnunciados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosEjercicio")
	public Set<Audio> getAudios() {
		return this.audios;
	}

	public void setAudios(Set<Audio> audios) {
		this.audios = audios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosEjercicio")
	public Set<Imagen> getImagens() {
		return this.imagens;
	}

	public void setImagens(Set<Imagen> imagens) {
		this.imagens = imagens;
	}

}
