package dl;
// Generated 23-nov-2016 15:49:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Respuesta generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name="Respuesta.findAll", query="SELECT r FROM Respuesta r"),
	@NamedQuery(name="Respuesta.findAllByDatosEjercicio", query="SELECT r FROM Respuesta r  WHERE r.datosEjercicio= :datosEjercicio")
})
@Table(name = "RESPUESTA")
public class Respuesta implements java.io.Serializable {

	private Integer idRespuesta;
	private DatosEjercicio datosEjercicio;
	private String textoRespuesta;

	public Respuesta() {
	}

	public Respuesta(DatosEjercicio datosEjercicio, String textoRespuesta) {
		this.datosEjercicio = datosEjercicio;
		this.textoRespuesta = textoRespuesta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idRESPUESTA", unique = true, nullable = false)
	public Integer getIdRespuesta() {
		return this.idRespuesta;
	}

	public void setIdRespuesta(Integer idRespuesta) {
		this.idRespuesta = idRespuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDATOS_EJERCICIO", nullable = false)
	public DatosEjercicio getDatosEjercicio() {
		return this.datosEjercicio;
	}

	public void setDatosEjercicio(DatosEjercicio datosEjercicio) {
		this.datosEjercicio = datosEjercicio;
	}

	@Column(name = "TEXTO_RESPUESTA", nullable = false, length = 45)
	public String getTextoRespuesta() {
		return this.textoRespuesta;
	}

	public void setTextoRespuesta(String textoRespuesta) {
		this.textoRespuesta = textoRespuesta;
	}

}
