package dl;
// Generated 23-nov-2016 15:49:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Resultados generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name="Resultados.findAll", query="SELECT re FROM Resultados re"),
	@NamedQuery(name="Resultados.findByUsers", query="SELECT re FROM Resultados re  WHERE re.usuarios= :usuarios"),
	@NamedQuery(name="Resultados.findByEjercicioANDUsers", query="SELECT re FROM Resultados re  WHERE re.usuarios= :usuarios AND re.datosEjercicio= :datosEjercicio")
})
@Table(name = "RESULTADOS")
public class Resultados implements java.io.Serializable {

	private Integer idResultados;
	private DatosEjercicio datosEjercicio;
	private Usuarios usuarios;
	private boolean aprobado;

	public Resultados() {
	}

	public Resultados(DatosEjercicio datosEjercicio, Usuarios usuarios, boolean aprobado) {
		this.datosEjercicio = datosEjercicio;
		this.usuarios = usuarios;
		this.aprobado = aprobado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idRESULTADOS", unique = true, nullable = false)
	public Integer getIdResultados() {
		return this.idResultados;
	}

	public void setIdResultados(Integer idResultados) {
		this.idResultados = idResultados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDATOS_EJERCICIO", nullable = false)
	public DatosEjercicio getDatosEjercicio() {
		return this.datosEjercicio;
	}

	public void setDatosEjercicio(DatosEjercicio datosEjercicio) {
		this.datosEjercicio = datosEjercicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "APROBADO", nullable = false)
	public boolean isAprobado() {
		return this.aprobado;
	}

	public void setAprobado(boolean aprobado) {
		this.aprobado = aprobado;
	}

}
