package dl;
// Generated 23-nov-2016 15:49:48 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name="Usuarios.findAllById", query="SELECT u FROM Usuarios u  WHERE u.idUser= :idUser"),
	@NamedQuery(name="Usuarios.findByUsername", query="SELECT u FROM Usuarios u WHERE u.username= :username"),
	@NamedQuery(name="Usuarios.findAll", query="SELECT u FROM Usuarios u")
})
@Table(name = "USUARIOS")
public class Usuarios implements java.io.Serializable {

	private Integer idUser;
	private String nombre;
	private String apellidos;
	private Integer edad;
	private String foto;
	private String aficiones;
	private String username;
	private String password;
	private Set<Resultados> resultadoses = new HashSet<Resultados>(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String apellidos, Integer edad, String foto, String aficiones, String username,
			String password, Set<Resultados> resultadoses) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.edad = edad;
		this.foto = foto;
		this.aficiones = aficiones;
		this.username = username;
		this.password = password;
		this.resultadoses = resultadoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", length = 45)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "foto", length = 45)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Column(name = "aficiones", length = 45)
	public String getAficiones() {
		return this.aficiones;
	}

	public void setAficiones(String aficiones) {
		this.aficiones = aficiones;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Resultados> getResultadoses() {
		return this.resultadoses;
	}

	public void setResultadoses(Set<Resultados> resultadoses) {
		this.resultadoses = resultadoses;
	}

}
